spring:
  application:
    name: site-api
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://101.43.164.174:8888/auth/realms/spring-boot-quickstart/protocol/openid-connect/certs
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
server:
  port: 9092
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    show-details: always