"""
Django settings for Services project.

Generated by 'django-admin startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-%=#q_f*14@+=@vr9=lfys+1jqe3u^@pa^_)@du+$*rjj$=yi^0'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'api.apps.ApiConfig',
    # 'mozilla_django_oidc',  # Load after auth
]

# # Add 'mozilla_django_oidc' authentication backend
# AUTHENTICATION_BACKENDS = (
#     # 'mozilla_django_oidc.auth.OIDCAuthenticationBackend',
#     # ...
#     'Services.auth.MyAuthenticationBackend',
#     'django.contrib.auth.backends.ModelBackend',
# )


REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE': 10
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django-keycloak-auth.middleware.KeycloakMiddleware',
]

# Exempt URIS
# For example: ['core/banks', 'swagger']
KEYCLOAK_EXEMPT_URIS = []
KEYCLOAK_CONFIG = {
    'KEYCLOAK_SERVER_URL': 'http://101.43.164.174:8888/auth',
    'KEYCLOAK_REALM': 'spring-boot-quickstart',
    'KEYCLOAK_CLIENT_ID': 'app-authz-rest-springboot',
    'KEYCLOAK_CLIENT_SECRET_KEY': 'c37a0929-484d-4635-a41c-f3eb93519bf2'
}

# OIDC_RP_CLIENT_ID = 'app-authz-rest-springboot'
# OIDC_RP_CLIENT_SECRET = 'c37a0929-484d-4635-a41c-f3eb93519bf2'
# OIDC_OP_TOKEN_ENDPOINT = 'http://101.43.164.174:8888/auth/realms/spring-boot-quickstart/protocol/openid-connect/token'
# OIDC_OP_AUTHORIZATION_ENDPOINT = 'http://101.43.164.174:8888/auth/realms/spring-boot-quickstart/protocol/openid-connect/auth'
# OIDC_OP_USER_ENDPOINT = 'http://101.43.164.174:8888/auth/realms/spring-boot-quickstart/protocol/openid-connect/userinfo'
# OIDC_OP_JWKS_ENDPOINT = 'http://101.43.164.174:8888/auth/realms/spring-boot-quickstart/protocol/openid-connect/certs'
# # Your OIDC server
# OIDC_HOST = "http://101.43.164.174:8888/"

# # Your OIDC realm
# OIDC_REALM = "spring-boot-quickstart"
# # Additional URL for registration
# OIDC_OP_REGISTRATION_ENDPOINT = "http://101.43.164.174:8888/auth/realms/spring-boot-quickstart/clients-registrations/openid-connect"
# OIDC_CREATE_USER = False


ROOT_URLCONF = 'Services.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Services.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': BASE_DIR / 'db.sqlite3',
    # }
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'OPTIONS': {
            'options': '-c search_path=pandanus',
        },
        'NAME': 'pandanus',
        'USER': 'pandanus',
        'PASSWORD': 'pandanus',
        'HOST': '127.0.0.1',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
